#!/bin/bash
NAME=example
docker build -t interlock-plugin-$NAME -f Dockerfile.build .
docker run --rm -v $(pwd):/go/src/github.com/ehazlett/interlock-plugins/example -v /var/run/docker.sock:/var/run/docker.sock interlock-plugin-$NAME make build image
